// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source=ports.go -destination=mocks/mock_ports.go -package=appmocks
//

// Package appmocks is a generated GoMock package.
package appmocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/ducnd58233/unified-document-viewer/internal/documentviewer/modules/audit/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAccessRecorder is a mock of AccessRecorder interface.
type MockAccessRecorder struct {
	ctrl     *gomock.Controller
	recorder *MockAccessRecorderMockRecorder
	isgomock struct{}
}

// MockAccessRecorderMockRecorder is the mock recorder for MockAccessRecorder.
type MockAccessRecorderMockRecorder struct {
	mock *MockAccessRecorder
}

// NewMockAccessRecorder creates a new mock instance.
func NewMockAccessRecorder(ctrl *gomock.Controller) *MockAccessRecorder {
	mock := &MockAccessRecorder{ctrl: ctrl}
	mock.recorder = &MockAccessRecorderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccessRecorder) EXPECT() *MockAccessRecorderMockRecorder {
	return m.recorder
}

// Record mocks base method.
func (m *MockAccessRecorder) Record(ctx context.Context, e domain.AccessEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Record", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// Record indicates an expected call of Record.
func (mr *MockAccessRecorderMockRecorder) Record(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Record", reflect.TypeOf((*MockAccessRecorder)(nil).Record), ctx, e)
}
