// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "components": {
        "schemas": {
            "dto.Document": {
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "issued_at": {
                        "type": "string"
                    },
                    "source": {
                        "type": "string"
                    },
                    "title": {
                        "type": "string"
                    },
                    "type": {
                        "type": "string"
                    },
                    "url": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "dto.DocumentsResponse": {
                "properties": {
                    "documents": {
                        "items": {
                            "$ref": "#/components/schemas/dto.Document"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "partial": {
                        "type": "boolean"
                    },
                    "request_id": {
                        "type": "string"
                    },
                    "served_from_cache": {
                        "type": "boolean"
                    },
                    "sources": {
                        "items": {
                            "$ref": "#/components/schemas/dto.Source"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "stale": {
                        "type": "boolean"
                    },
                    "vin": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "dto.ErrorBody": {
                "properties": {
                    "code": {
                        "type": "string"
                    },
                    "message": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "dto.ErrorResponse": {
                "properties": {
                    "error": {
                        "$ref": "#/components/schemas/dto.ErrorBody"
                    }
                },
                "type": "object"
            },
            "dto.Source": {
                "properties": {
                    "document_count": {
                        "type": "integer"
                    },
                    "error": {
                        "$ref": "#/components/schemas/dto.SourceError"
                    },
                    "latency_ms": {
                        "type": "integer"
                    },
                    "name": {
                        "type": "string"
                    },
                    "status": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "dto.SourceError": {
                "properties": {
                    "code": {
                        "type": "string"
                    },
                    "message": {
                        "type": "string"
                    }
                },
                "type": "object"
            }
        }
    },
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "version": "{{.Version}}"
    },
    "externalDocs": {
        "description": "",
        "url": ""
    },
    "paths": {
        "/vehicles/{vin}/documents": {
            "get": {
                "parameters": [
                    {
                        "description": "Vehicle identification number",
                        "in": "path",
                        "name": "vin",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Actor recorded on the audit trail",
                        "in": "header",
                        "name": "X-Actor-Id",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Caller correlation id",
                        "in": "header",
                        "name": "X-Request-Id",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/dto.DocumentsResponse"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/dto.ErrorResponse"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "503": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/dto.ErrorResponse"
                                }
                            }
                        },
                        "description": "Service Unavailable"
                    }
                },
                "summary": "List documents for a VIN"
            }
        }
    },
    "openapi": "3.1.0",
    "servers": [
        {
            "url": "/api/v1"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Title:            "Unified Document Viewer API",
	Description:      "Aggregates a vehicle's documents from the Sales and Service systems (Scenario D).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
