// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source=ports.go -destination=mocks/mock_ports.go -package=appmocks
//

// Package appmocks is a generated GoMock package.
package appmocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/ducnd58233/unified-document-viewer/internal/documentviewer/modules/documents/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockDocumentSource is a mock of DocumentSource interface.
type MockDocumentSource struct {
	ctrl     *gomock.Controller
	recorder *MockDocumentSourceMockRecorder
	isgomock struct{}
}

// MockDocumentSourceMockRecorder is the mock recorder for MockDocumentSource.
type MockDocumentSourceMockRecorder struct {
	mock *MockDocumentSource
}

// NewMockDocumentSource creates a new mock instance.
func NewMockDocumentSource(ctrl *gomock.Controller) *MockDocumentSource {
	mock := &MockDocumentSource{ctrl: ctrl}
	mock.recorder = &MockDocumentSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDocumentSource) EXPECT() *MockDocumentSourceMockRecorder {
	return m.recorder
}

// Fetch mocks base method.
func (m *MockDocumentSource) Fetch(ctx context.Context, vin string) ([]domain.Document, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", ctx, vin)
	ret0, _ := ret[0].([]domain.Document)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fetch indicates an expected call of Fetch.
func (mr *MockDocumentSourceMockRecorder) Fetch(ctx, vin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockDocumentSource)(nil).Fetch), ctx, vin)
}

// Name mocks base method.
func (m *MockDocumentSource) Name() domain.SourceName {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(domain.SourceName)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockDocumentSourceMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockDocumentSource)(nil).Name))
}

// MockDocumentCache is a mock of DocumentCache interface.
type MockDocumentCache struct {
	ctrl     *gomock.Controller
	recorder *MockDocumentCacheMockRecorder
	isgomock struct{}
}

// MockDocumentCacheMockRecorder is the mock recorder for MockDocumentCache.
type MockDocumentCacheMockRecorder struct {
	mock *MockDocumentCache
}

// NewMockDocumentCache creates a new mock instance.
func NewMockDocumentCache(ctrl *gomock.Controller) *MockDocumentCache {
	mock := &MockDocumentCache{ctrl: ctrl}
	mock.recorder = &MockDocumentCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDocumentCache) EXPECT() *MockDocumentCacheMockRecorder {
	return m.recorder
}

// Lookup mocks base method.
func (m *MockDocumentCache) Lookup(ctx context.Context, vin string) (domain.CachedResult, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lookup", ctx, vin)
	ret0, _ := ret[0].(domain.CachedResult)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Lookup indicates an expected call of Lookup.
func (mr *MockDocumentCacheMockRecorder) Lookup(ctx, vin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lookup", reflect.TypeOf((*MockDocumentCache)(nil).Lookup), ctx, vin)
}

// Store mocks base method.
func (m *MockDocumentCache) Store(ctx context.Context, vin string, r domain.AggregateResult, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, vin, r, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockDocumentCacheMockRecorder) Store(ctx, vin, r, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockDocumentCache)(nil).Store), ctx, vin, r, ttl)
}
